### ISSUE TITLE
Output data gets nulled between solves

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/GrasshopperAsyncComponent#2]
During processing, output data is set to null. We should keep the old one, and replace it only when the new is set, or on the component erroring out.

**Comment by AlanRynne** [comment]
I can give this a shot this afternoon. I agree that it should keep the previous data until it finishes computing/fetching. Although that might lead to partial results down the line:

> Imagine, 2 receivers that take different times to upload (say 1sec and 10sec), if results in GH are not emptied per run, it will result in components down the line executing when the first receiver finishes (1s) and then when the second finishes (10s).
Leaving them "Empty" while they load will have more consistent behaviour (at the cost of loosing the data). Maybe we could provide an option for this in the dropdown menu?

On another note, when it errors out, data should be empty (orange GH cable) instead of just passing a Null, this would prevent other components down the line from executing, as `null` is still a valid value in GH.

**Comment by didimitrie** [comment]
Yeah, it's actually orange - just like the current US president - so `empty` not actually `null`! I know that by bypassing gh's natural execution policies, we screw up the graph resolution and things get wonky as per the example you described. I'm not sure whether this has an elegant solution within `1.0` (grasshopper, not speckle). Looking forward to you giving it a shot!

**Comment by didimitrie** [comment]
I think I got this. Both re #3. We can prevent the ominous "flash of null data" by simply doing:

```cs
    protected override void ExpireDownStreamObjects()
    {
      if (SetData)
        base.ExpireDownStreamObjects();
    }
```

in the parent component. It's so ridiculously simple I'm facepalming myself. Please don't tell @sbaer that we solved it.
